# 2-D FEM shape functions

Compute the shape functions at try the interpolation at different "integration" pints within the element.

In [ ]:
import numpy as np

In [ ]:
#def shapes():
#    
#    N1 = ?
#    N2 = ?
#    N3 = ?
#    N4 = ?

#    N = np.array([N1, N2, N3, N4])
    
#    return N

In [12]:
#hide: the code in this cell is hidden by the author

In [18]:
# pseudo gcoord
GCOORD = np.array([[-1, 1, 1, -1],[-1, -1, 1, 1]])

print(GCOORD)
# pseudo nodal temperatures
T = np.array([0, 0, 1, 1])

# interpolatin point
xi = 0
eta = 0

# shape functions at integration point
N = shapes()

#interpolation
print(sum(N*T))

[[-1  1  1 -1]
 [-1 -1  1  1]]
[0.25 0.25 0.25 0.25]
0.5
