# 2-D FEM coordinate and connectivity matrices

In [3]:
import numpy as np

Let's first create the global coordinate vector. The columns refer to the nodes, and the rows to the x,y coordinates. 

In [72]:
lx          = 1
ly          = 1
nx          = 4
ny          = 4
nnodel      = 4
dx          = lx/(nx-1)
dy          = ly/(ny-1)

nex         = nx-1
ney         = ny-1
nnod        = nx*ny
nel         = nex*ney
GCOORD      = np.zeros((nnod,2))

id = 0

for i in range(0,ny):
    for j in range(0,nx):
        GCOORD[id,0] = j*dx;
        GCOORD[id,1] = i*dy;
        id          = id + 1;
                       
print(GCOORD)
GCOORD.shape


[[0.         0.        ]
 [0.33333333 0.        ]
 [0.66666667 0.        ]
 [1.         0.        ]
 [0.         0.33333333]
 [0.33333333 0.33333333]
 [0.66666667 0.33333333]
 [1.         0.33333333]
 [0.         0.66666667]
 [0.33333333 0.66666667]
 [0.66666667 0.66666667]
 [1.         0.66666667]
 [0.         1.        ]
 [0.33333333 1.        ]
 [0.66666667 1.        ]
 [1.         1.        ]]


(16, 2)

Now we do the connectivity:

In [73]:
E2N   = np.zeros((nel,nnodel), dtype=int)

for iel in range(0,nel):
    col        = np.ceil((iel+1)/ney)
    ind        = iel + col-1
    E2N[iel,:] = [ind, ind+ny, ind+ny+1, ind+1]


print(E2N)
print(E2N.shape)
# x coordinates of first element
# insights into indexing: https://kanoki.org/2020/07/05/numpy-index-array-with-another-array/
# https://realpython.com/numpy-array-programming/
# and something on ordering arrays
# https://stackoverflow.com/questions/26998223/what-is-the-difference-between-contiguous-and-non-contiguous-arrays
print(np.take(GCOORD[:,0], E2N[0,:]))

  

[[ 0  4  5  1]
 [ 1  5  6  2]
 [ 2  6  7  3]
 [ 4  8  9  5]
 [ 5  9 10  6]
 [ 6 10 11  7]
 [ 8 12 13  9]
 [ 9 13 14 10]
 [10 14 15 11]]
(9, 4)
[0.         0.         0.33333333 0.33333333]


In [53]:
A = np.array([[0.32, 0.35, 0.88, 0.63, 1.  ],
              [0.23, 0.69, 0.98, 0.22, 0.96],
              [0.7 , 0.51, 0.09, 0.58, 0.19],
              [0.98, 0.42, 0.62, 0.94, 0.46],
              [0.48, 0.59, 0.17, 0.23, 0.98]])
print(A.shape)
B = np.array([[4, 0, 3, 2, 1],
              [3, 2, 4, 1, 0],
              [4, 3, 0, 2, 1],
              [4, 2, 0, 3, 1],
              [0, 3, 1, 2, 4]])

(5, 5)


In [56]:
m,n = A.shape
B + n*np.arange(m)[:,None]
np.take(A,B + n*np.arange(m)[:,None])

array([[1.  , 0.32, 0.63, 0.88, 0.35],
       [0.22, 0.98, 0.96, 0.69, 0.23],
       [0.19, 0.58, 0.7 , 0.09, 0.51],
       [0.46, 0.62, 0.98, 0.94, 0.42],
       [0.48, 0.23, 0.59, 0.17, 0.98]])

In [49]:
B + n*np.arange(m)[:,None]

array([[ 4,  0,  3,  2,  1],
       [ 8,  7,  9,  6,  5],
       [14, 13, 10, 12, 11],
       [19, 17, 15, 18, 16],
       [20, 23, 21, 22, 24]])

In [69]:
B = np.arange(4)
B = B.reshape(2,2)
print(B)


[[0 1]
 [2 3]]


In [68]:
print(B[1,0])

2
